package com.payitezy.domain;

// Generated Feb 25, 2016 4:21:22 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Marchant generated by hbm2java
 */
@Entity
@Table(name = "marchant", catalog = "PayitEzy")
public class Merchant extends AbstractDomain implements java.io.Serializable {

    private String marchantName;
    private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Merchant() {
    }

    public Merchant(final String id, final String marchantName) {
        this.id = id;
        this.marchantName = marchantName;
    }

    public Merchant(final String id, final String marchantName, final Set<Transaction> transactions) {
        this.id = id;
        this.marchantName = marchantName;
        this.transactions = transactions;
    }

    @Column(name = "marchant_name", nullable = false, length = 45)
    public String getMarchantName() {
        return marchantName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "marchant")
    public Set<Transaction> getTransactions() {
        return transactions;
    }

    public void setMarchantName(final String marchantName) {
        this.marchantName = marchantName;
    }

    public void setTransactions(final Set<Transaction> transactions) {
        this.transactions = transactions;
    }

}
