package com.payitezy.domain;

// Generated Feb 25, 2016 4:21:22 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "PayitEzy")
public class Transaction extends AbstractDomain implements java.io.Serializable {

    private Merchant marchant;
    private Users users;
    private String source;
    private String channel;
    private Date amountReceivedDate;
    private String status;
    private String marchantPercentage;
    private String orderId;

    public Transaction() {
    }

    public Transaction(final String id, final Merchant marchant, final Users users, final String source, final String channel,
            final Date amountReceivedDate, final String status, final String marchantPercentage, final String orderId) {
        this.id = id;
        this.marchant = marchant;
        this.users = users;
        this.source = source;
        this.channel = channel;
        this.amountReceivedDate = amountReceivedDate;
        this.status = status;
        this.marchantPercentage = marchantPercentage;
        this.orderId = orderId;
    }

    public Transaction(final String id, final Merchant marchant, final Users users, final String source, final String status,
            final String orderId) {
        this.id = id;
        this.marchant = marchant;
        this.users = users;
        this.source = source;
        this.status = status;
        this.orderId = orderId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "amount_received_date", length = 19)
    public Date getAmountReceivedDate() {
        return amountReceivedDate;
    }

    @Column(name = "channel", length = 45)
    public String getChannel() {
        return channel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "marchant_id1", nullable = false)
    public Merchant getMarchant() {
        return marchant;
    }

    @Column(name = "marchant_percentage", length = 45)
    public String getMarchantPercentage() {
        return marchantPercentage;
    }

    @Column(name = "order_id", nullable = false, length = 100)
    public String getOrderId() {
        return orderId;
    }

    @Column(name = "source", nullable = false, length = 45)
    public String getSource() {
        return source;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id1", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setAmountReceivedDate(final Date amountReceivedDate) {
        this.amountReceivedDate = amountReceivedDate;
    }

    public void setChannel(final String channel) {
        this.channel = channel;
    }

    public void setMarchant(final Merchant marchant) {
        this.marchant = marchant;
    }

    public void setMarchantPercentage(final String marchantPercentage) {
        this.marchantPercentage = marchantPercentage;
    }

    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    public void setSource(final String source) {
        this.source = source;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
