package com.payitezy.domain;

// Generated Feb 25, 2016 4:21:22 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "PayitEzy")
public class Users extends AbstractDomain implements java.io.Serializable {

    private String userName;
    private String userType;
    private String emailId;
    private String phoneNo;
    private Date dob;
    private String gender;
    private String password;
    private String status;
    private String userCode;
    private String authenticateStatus;
    private long userCount;
    private Date createdDate;
    private String emailStatus;
    private String source;
    private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Users() {
    }

    public Users(final Users user) {
        id = user.id;
        userName = user.userName;
        userType = user.userType;
        emailId = user.emailId;
        phoneNo = user.phoneNo;
        password = user.password;
        status = user.status;
        userCode = user.userCode;
        userCount = user.userCount;

    }
    public Users(final String id, final String userName, final String userType, final String emailId, final String phoneNo, final Date dob,
            final String gender, final String password, final String status, final String userCode, final String authenticateStatus,
            final long userCount, final Date createdDate, final String emailStatus, final String source) {
        this.id = id;
        this.userName = userName;
        this.userType = userType;
        this.emailId = emailId;
        this.phoneNo = phoneNo;
        this.dob = dob;
        this.gender = gender;
        this.password = password;
        this.status = status;
        this.userCode = userCode;
        this.authenticateStatus = authenticateStatus;
        this.userCount = userCount;
        this.createdDate = createdDate;
        this.emailStatus = emailStatus;
        this.source = source;
        
    }

    public Users(final String id, final String userName, final String userType, final String emailId, final String phoneNo,
            final String password, final String status, final String userCode, final long userCount, final String source) {
        this.id = id;
        this.userName = userName;
        this.userType = userType;
        this.emailId = emailId;
        this.phoneNo = phoneNo;
        this.password = password;
        this.status = status;
        this.userCode = userCode;
        this.userCount = userCount;
        this.source = source;
    }

    @Column(name = "authenticate_status", length = 45)
    public String getAuthenticateStatus() {
        return authenticateStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "dob", length = 45)
    public Date getDob() {
        return dob;
    }

    @Column(name = "email_id", nullable = false, length = 45)
    public String getEmailId() {
        return emailId;
    }

    @Column(name = "email_status", length = 45)
    public String getEmailStatus() {
        return emailStatus;
    }

    @Column(name = "gender", length = 45)
    public String getGender() {
        return gender;
    }

    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
        return password;
    }

    @Column(name = "phone_no", nullable = false, length = 45)
    public String getPhoneNo() {
        return phoneNo;
    }

    @Column(name = "source", nullable = false, length = 45)
    public String getSource() {
        return source;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

   

    @Column(name = "user_code", nullable = false, length = 45)
    public String getUserCode() {
        return userCode;
    }

    @Column(name = "user_count", nullable = false)
    public long getUserCount() {
        return userCount;
    }

    @Column(name = "user_name", nullable = false, length = 45)
    public String getUserName() {
        return userName;
    }

    @Column(name = "user_type", nullable = false, length = 45)
    public String getUserType() {
        return userType;
    }

    public void setAuthenticateStatus(final String authenticateStatus) {
        this.authenticateStatus = authenticateStatus;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDob(final Date dob) {
        this.dob = dob;
    }

    public void setEmailId(final String emailId) {
        this.emailId = emailId;
    }

    public void setEmailStatus(final String emailStatus) {
        this.emailStatus = emailStatus;
    }

    public void setGender(final String gender) {
        this.gender = gender;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setPhoneNo(final String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public void setSource(final String source) {
        this.source = source;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    

    public void setUserCode(final String userCode) {
        this.userCode = userCode;
    }

    public void setUserCount(final long userCount) {
        this.userCount = userCount;
    }

    public void setUserName(final String userName) {
        this.userName = userName;
    }

    public void setUserType(final String userType) {
        this.userType = userType;
    }
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Transaction> getTransactions() {
		return transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
